#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [3]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.4, random_state=56)

In [5]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [6]:
print(reg.intercept_)
print(reg.coef_)

[-4.4935837 -2.018135 ]
[[-0.3747708   0.84563017  0.73464453]
 [-0.28605554  0.7941562   0.9224192 ]]


In [7]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[ 20.823742  37.082428]
 [118.82518  133.01227 ]
 [102.252846 119.05237 ]
 [ 20.823742  37.082428]
 [ 82.834984 100.87138 ]
 [ 82.834984 100.87138 ]] 

[[ 22.  37.]
 [119. 133.]
 [103. 119.]
 [ 22.  37.]
 [ 81. 101.]
 [ 81. 101.]]


In [8]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 0.8449887
