#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.80364278, 0.41020101],
       [0.75321472, 0.65594496],
       [0.65492789, 0.97234576]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([1.97691661, 0.50514887])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[139.2701249  116.2090025 ]
 [183.30668973 157.78672576]
 [210.81042824 180.48531552]
 [140.5690449  106.52807802]
 [175.5818337  159.84393786]
 [139.2701249  116.2090025 ]
 [183.30668973 157.78672576]
 [210.81042824 180.48531552]
 [140.5690449  106.52807802]
 [175.5818337  159.84393786]
 [139.2701249  116.2090025 ]
 [183.30668973 157.78672576]
 [210.81042824 180.48531552]
 [140.5690449  106.52807802]
 [175.5818337  159.84393786]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(5927.370840496429, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 5927.370840496429
 
 Epoch count: 1 
 Loss value: 3817.3828738199168
 
 Epoch count: 2 
 Loss value: 2484.11964766029
 
 Epoch count: 3 
 Loss value: 1638.3971652046973
 
 Epoch count: 4 
 Loss value: 1099.103804650493
 
 Epoch count: 5 
 Loss value: 752.7620310189199
 
 Epoch count: 6 
 Loss value: 528.2273672722663
 
 Epoch count: 7 
 Loss value: 380.85754179772135
 
 Epoch count: 8 
 Loss value: 282.6064628363154
 
 Epoch count: 9 
 Loss value: 215.8250239281935
 
 Epoch count: 10 
 Loss value: 169.38113631063894
 
 Epoch count: 11 
 Loss value: 136.2308782779903
 
 Epoch count: 12 
 Loss value: 111.89764865355538
 
 Epoch count: 13 
 Loss value: 93.51953170739858
 
 Epoch count: 14 
 Loss value: 79.25228002013574
 
 Epoch count: 15 
 Loss value: 67.89489960368083
 
 Epoch count: 16 
 Loss value: 58.65460736258544
 
 Epoch count: 17 
 Loss value: 50.99907870140417
 
 Epoch count: 18 
 Loss value: 44.563390677317884
 
 Epoch count: 19 
 Loss value: 39.